### ISSUE TITLE
Error when trying to call a contract

### ISSUE THREAD

**Issue by cds95** [graphprotocol/graph-ts#235]
Hi I'm getting this error when trying to call a contract's function in my event handler.

```
Could not find ABI for contract "Vault", try adding it to the 'abis' section of the subgraph manifest wasm backtrace: 0: 0x27b2 - <unknown>!src/app/handleDepositEth , code: SubgraphSyncingFailure
```

I've already added the ABI for the contract `Vault` in my `abis` folder and have also defined it as a `template` in my `subgraph.yaml` file.  Anyone have any ideas on what's going wrong?

Thanks in advance.

How I'm calling it

```
let vaultContract = VaultTemplate.bind(
    Address.fromString(vault.address.toHexString())
  );
let currentLpValue = vaultContract.getAmountETH(eighteenDP); --> This line errors
```

My `subgraph.yaml`

```
specVersion: 0.0.2
description: Sample subgraph
schema:
  file: ./schema.graphql
...other data sources
templates:
  - kind: ethereum/contract
    name: Vault
    network: "rinkeby"
    source:
      abi: Vault
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - Vault
      abis:
        - name: Vault
          file: ./abis/Vault.json
      eventHandlers: []
      file: ./src/vaults.ts

```
