### ISSUE TITLE
How can I get network name into mapping.ts

### ISSUE THREAD

**Issue by longhoangwkm** [graphprotocol/graph-ts#277]
```
dataSources:
  - kind: ethereum
    name: Contract
    network: rinkeby
```

I would like to get `dataSources.network` or chainId inside mapping but can not find any method, Thanks
